trigger: none
pr: none
pool:
  vmImage: ubuntu-latest
stages:

  - stage: deployInfrastructure
    displayName: Deploy infrastructure
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: $(subscriptionName)
          locationName: $(locationName)
          appInsightsLocation: $(appInsightsLocation)
          environmentName: $(environmentName)
          subscriptionId: $(subscriptionId)
          applicationCode: $(applicationCode)
          applicationShortCode: $(applicationShortCode)
          environmentCategory: $(environmentCategory)
          kubernetesVersion: $(kubernetesVersion)
          sendgridEmail: $(sendGridEmail)
          sysAdmins: $(sysAdmins)
          aksAgentVmSize: $(aksAgentVmSize)
          azureDevOpsProjectId: serenity-POC
          testPipelineId: 453
          runVersion: specific
          testPipelineRunId: $(testPipelineRunId)
          isHelmVersion3: true
          aadSGId: $(aadSGId)
          telemetryStorageType: $(telemetryStorageType)