trigger: none
pr: none
schedules:
- cron: 0 12 1,15 * *
  branches:
    include:
    - secret-expiration
pool:
  vmImage: ubuntu-latest
stages:
  - stage: checkParameters
    displayName: Check parameters
    dependsOn: []
    jobs:
      - job: checkParameters
        displayName: Check parameters
        steps:
          - checkout: none

          - script: |-
              set -Eeuxo pipefail
              echo "Subscription name: '$(subscriptionName)'"
              if [ -z "$(subscriptionName)" ]
              then
                echo "A value for the 'subscriptionName' variable must be provided" > /dev/stderr
                exit 1
              fi

              echo "Sendgrid API Key: '$(sendgridAPIKey)'"
              if [ -z "$(sendgridAPIKey)" ]
              then
                echo "A value for the 'sendgridAPIKey' variable must be provided" > /dev/stderr
                exit 1
              fi

              echo "destEmailAddress: '$(destEmailAddress)'"
              if [ -z "$(destEmailAddress)" ]
              then
                echo "A value for the 'destEmailAddress' variable must be provided" > /dev/stderr
                exit 1
              fi
            displayName: Check parameters
      
      - job: notify
        displayName: Notify expiration details
        pool:
          vmImage: windows-latest
        dependsOn:
          - checkParameters
        
        steps:
          - checkout: self
            displayName: checkout repository

          - task: AzureCLI@2
            displayName: 'Notify expiration details'
            inputs:
              azureSubscription: $(subscriptionName)
              scriptType: ps
              scriptPath: 'pipelines/cd/secret-expiration.ps1'
              arguments: '-sendgridAPIKey $(sendgridAPIKey) -destEmailAddress $(destEmailAddress)'